language: php
php:
  - "7.0"

env:
  global:
    - DATABASE='drupal'
    - DB_USERNAME='root'
    - DB_ENCODE='utf8'

services:
  - mysql

mysql:
  database: $DATABASE
  username: $DB_USERNAME
  encoding: $DB_ENCODE

before_script:
  - /bin/bash scripts/travis.sh

script:
  - composer test
