language: php
php:
  - 7.0

addons:
  apt:
    packages:
      - php5-cgi
      - php5-mysql

env:
  global:
    - DATABASE='drupal'
    - DB_USERNAME='root'
    - DB_ENCODE='utf8'

mysql:
  database: $DATABASE
  username: $DB_USERNAME
  encoding: $DB_ENCODE

before_script:
  - npm i phantomjs-prebuilt
  - ./node_modules/.bin/phantomjs --webdriver=8643 &
  - composer install
  - php -d sendmail_path=`which true` ./vendor/bin/drush si drupalcamp_profile --db-url="mysql://$DB_USERNAME@127.0.0.1/$DATABASE" -y
  - ./vendor/bin/drush cset system.site uuid 2fc27f02-a284-417f-9daa-abaf62cc3bba -y
  - ./vendor/bin/drush cim -y
  - ./vendor/bin/drush rs 127.0.0.1:8888 &
  - ./vendor/bin/wait-for-listen 8888
  - ./vendor/bin/wait-for-listen 8643

script:
  - composer test
