language: php
php:
  - "7.1"

env:
  global:
    - DATABASE='drupal'
    - DB_USERNAME='root'
    - DB_ENCODE='utf8'

services:
  - mysql

mysql:
  database: $DATABASE
  username: $DB_USERNAME
  encoding: $DB_ENCODE

before_install:
  - nvm install 12
  - nvm use 12

before_script:
  - composer self-update --1
  - /bin/bash scripts/travis.sh

script:
  - composer test
