parameters:
  renderer.config:
    required_cache_contexts: ['languages:language_interface', 'theme', 'user.permissions', 'url.site']
    auto_placeholder_conditions:
      max-age: 0
      contexts: ['session', 'user']
      tags: []
